name: Mirror Organization Repo to Personal Repo

on:
  push:
    branches:
      - main
    paths:
      - 'path/to/files/**'  # If you want to target specific files

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from the org repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add personal repo remote
        run: |
          # Ensure the PAT is correctly masked
          echo "::add-mask::${{ secrets.PERSONAL_PAT }}"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_PAT }}@github.com/JMJones716/Staff-Website-MMP.git

      - name: Debug: Check remote URL
        run: |
          git remote -v

      - name: Push to personal repo
        run: |
          git push origin main
