name: Mirror to Personal Repo

on:
  push:
    branches:
      - main
    # Trigger on push to the main branch of the org repo

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from the org repo
      uses: actions/checkout@v4
      with:
        # Checkout the code from the repo where the push happened
        ref: main

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Set up personal repo as remote
      run: |
        # URL encode the PAT secret for use in the remote URL
        ENCODED_PAT=$(echo "${{ secrets.PERSONAL_PAT }}" | jq -s -R -r @uri)
        echo "::add-mask::$ENCODED_PAT"  # Mask the PAT in logs
        # Set the remote URL to your personal repo (using the token for authentication)
        git remote set-url origin https://JMJones716:$ENCODED_PAT@github.com/JMJones716/Staff-Website-MMP.git

    - name: Push code to the personal repo
      run: |
        # Push the changes to the personal repo's main branch
        git push origin main
