name: Mirror Repository to Personal Repo

on:
  push:
    branches: [ main ]  # Change if you want to mirror a different branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history needed for --mirror

      - name: Encode PAT securely
        id: encode_pat
        env:
          PERSONAL_PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          ENCODED_PAT=$(python3 -c "import urllib.parse, os; print(urllib.parse.quote(os.environ['PERSONAL_PAT']))")
          echo "ENCODED_PAT=${ENCODED_PAT}" >> $GITHUB_OUTPUT

      - name: Debug - Add remote and show config
        run: |
          ENCODED_PAT="${{ steps.encode_pat.outputs.ENCODED_PAT }}"
          REMOTE_URL="https://JMJones716:${ENCODED_PAT}@github.com/JMJones716/Staff-Website-MMP.git"
          echo "Adding remote: $REMOTE_URL"
          git remote remove personal || true
          git remote add personal "$REMOTE_URL"
          echo "Configured remotes:"
          git remote -v

      - name: Debug - Test remote connection
        run: |
          ENCODED_PAT="${{ steps.encode_pat.outputs.ENCODED_PAT }}"
          REMOTE_URL="https://JMJones716:${ENCODED_PAT}@github.com/JMJones716/Staff-Website-MMP.git"
          echo "Testing git ls-remote..."
          GIT_CURL_VERBOSE=1 GIT_TRACE=1 git ls-remote "$REMOTE_URL"

      - name: Verify API access with curl
        env:
          PERSONAL_PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          echo "Testing GitHub API access..."
          curl -I -u "JMJones716:${PERSONAL_PAT}" https://api.github.com/repos/JMJones716/Staff-Website-MMP

      - name: Push full mirror to personal repo
        run: |
          ENCODED_PAT="${{ steps.encode_pat.outputs.ENCODED_PAT }}"
          REMOTE_URL="https://JMJones716:${ENCODED_PAT}@github.com/JMJones716/Staff-Website-MMP.git"
          echo "Pushing all refs to $REMOTE_URL"
          git remote remove personal || true
          git remote add personal "$REMOTE_URL"
          git push --mirror personal
