name: Mirror Repository to Personal Repo

on:
  push:
    branches: [ main ]  # Adjust if you wish to mirror a different branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full repo history is available

      - name: Debug - Clean PAT and show remote URL
        env:
          PERSONAL_PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          # Clean the PAT to remove any trailing whitespace or newlines.
          PAT_CLEAN=$(echo -n "${PERSONAL_PAT}")
          echo "DEBUG: PAT_CLEAN length is ${#PAT_CLEAN}"
          # Construct the remote URL.
          REMOTE_URL="https://JMJones716:${PAT_CLEAN}@github.com/JMJones716/Staff-Website-MMP.git"
          echo "DEBUG: Constructed remote URL is: ${REMOTE_URL}"
          # Remove any existing remote named 'personal'.
          git remote remove personal || true
          # Add the remote.
          git remote add personal "${REMOTE_URL}"
          # List current remotes.
          echo "DEBUG: Current remotes:"
          git remote -v

      - name: Debug - Verbose ls-remote on personal remote
        env:
          PERSONAL_PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          PAT_CLEAN=$(echo -n "${PERSONAL_PAT}")
          echo "DEBUG: Running verbose ls-remote on personal remote..."
          # This provides detailed output for the Git HTTPS call.
          GIT_CURL_VERBOSE=1 GIT_TRACE=1 git ls-remote https://JMJones716:${PAT_CLEAN}@github.com/JMJones716/Staff-Website-MMP.git

      - name: Verify repository access with curl
        env:
          PERSONAL_PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          PAT_CLEAN=$(echo -n "${PERSONAL_PAT}")
          echo "DEBUG: Testing repository access via API..."
          # The -I flag returns just the headers.
          curl -I -u "JMJones716:${PAT_CLEAN}" https://api.github.com/repos/JMJones716/Staff-Website-MMP

      - name: Mirror repository to personal repo
        env:
          PERSONAL_PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          PAT_CLEAN=$(echo -n "${PERSONAL_PAT}")
          echo "Mirroring using cleaned PAT..."
          git remote remove personal || true
          git remote add personal https://JMJones716:${PAT_CLEAN}@github.com/JMJones716/Staff-Website-MMP.git
          echo "DEBUG: Remotes before push:"
          git remote -v
          echo "Pushing all refs via mirror..."
          git push --mirror personal
